import type { PushFileDiff } from "../vcs/git.js";
import type { ReviewItem } from "./items.js";

/**
 * The review page: one self-contained HTML document, no framework, no CDN, no request to
 * anything but the loopback origin that served it.
 *
 * Generated by TypeScript rather than a template file so that it is testable — the suite
 * asserts that the findings are present, that a message containing `<script>` or a quote
 * cannot break out of the markup, and that the page will not submit without the token.
 */

/**
 * The five characters that can move a value from HTML text into HTML markup.
 *
 * `&` first and unconditionally, or escaping `<` to `&lt;` would then have its own `&`
 * escaped again. Quotes are included because attribute values are interpolated too (the
 * token, the file paths), and `'` because a single-quoted attribute is a legal thing for
 * this file to grow later — escaping only what today's quoting style needs is how a future
 * edit reintroduces the hole.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export type PageInput = {
  /** The repository's directory name — what a person calls it, not its absolute path. */
  repo: string;
  branch: string;
  base: string;
  /**
   * The message the commit will carry, from the agent's answer. Absent when `review` was
   * run without one, which is its own thing worth showing.
   */
  commitMessage?: string | undefined;
  /** `readPushDiffstat`'s answer: the size of what the push will deliver. */
  diffstat: string;
  items: ReviewItem[];
  files: PushFileDiff[];
  /** True when an `--input` response supplied readiness answers. */
  answered: boolean;
  /** Anything shipkit could not do, said plainly — e.g. the forge was unreachable. */
  notes: string[];
  /** The single-use secret the page must send back. Without it the POST is refused. */
  token: string;
  /** How long the command will wait, in whole minutes, so the page can say so. */
  waitMinutes: number;
};

const STYLE = `
:root { color-scheme: light dark; --fg:#1f2328; --bg:#ffffff; --muted:#59636e; --line:#d1d9e0;
  --card:#f6f8fa; --refuse:#cf222e; --warn:#9a6700; --inform:#0969da; --add:#e6ffec; --del:#ffebe9; }
@media (prefers-color-scheme: dark) { :root { --fg:#e6edf3; --bg:#0d1117; --muted:#9198a1;
  --line:#3d444d; --card:#151b23; --refuse:#ff7b72; --warn:#d29922; --inform:#4493f8;
  --add:#12261e; --del:#25171c; } }
* { box-sizing: border-box; }
body { margin:0; padding:0 0 88px; font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  color:var(--fg); background:var(--bg); }
main { max-width: 1000px; margin: 0 auto; padding: 24px 16px; }
header.page { border-bottom:1px solid var(--line); padding-bottom:16px; margin-bottom:24px; }
h1 { font-size:20px; margin:0 0 6px; }
h2 { font-size:15px; margin:28px 0 10px; }
.refs { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; color:var(--muted); }
.subject { margin:10px 0 0; font-weight:600; white-space:pre-wrap; }
.subject.none { font-weight:400; color:var(--muted); }
pre.stat { margin:10px 0 0; font-family: ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:12px; color:var(--muted); overflow-x:auto; }
.note-line { margin:10px 0 0; color:var(--warn); font-size:13px; }
.card { border:1px solid var(--line); border-left-width:4px; border-radius:6px;
  background:var(--card); padding:12px 14px; margin:0 0 10px; }
.card.refuses { border-left-color:var(--refuse); }
.card.warns  { border-left-color:var(--warn); }
.card.informs{ border-left-color:var(--inform); }
.card .top { display:flex; align-items:baseline; gap:8px; }
.card input[type=checkbox] { width:16px; height:16px; margin:2px 4px 0 0; flex:none; align-self:flex-start; }
.badge { font-size:11px; text-transform:uppercase; letter-spacing:.04em; font-weight:700; }
.card.refuses .badge { color:var(--refuse); }
.card.warns .badge { color:var(--warn); }
.card.informs .badge { color:var(--inform); }
.id { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12px; color:var(--muted); }
.msg { margin:6px 0 0 24px; white-space:pre-wrap; }
.card textarea { margin:8px 0 0 24px; width:calc(100% - 24px); min-height:38px; resize:vertical;
  font:inherit; padding:6px 8px; border:1px solid var(--line); border-radius:6px;
  background:var(--bg); color:var(--fg); }
.file { border:1px solid var(--line); border-radius:6px; margin:0 0 14px; overflow:hidden; }
.file > .head { display:flex; align-items:center; gap:10px; flex-wrap:wrap;
  background:var(--card); padding:8px 12px; border-bottom:1px solid var(--line); }
.file .path { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-weight:600; }
.file .status { font-size:11px; text-transform:uppercase; color:var(--muted); }
.file .spacer { flex:1; }
button { font:inherit; padding:4px 10px; border:1px solid var(--line); border-radius:6px;
  background:var(--bg); color:var(--fg); cursor:pointer; }
button.primary { background:var(--inform); border-color:var(--inform); color:#fff; font-weight:600;
  padding:8px 18px; }
button:disabled { opacity:.55; cursor:default; }
code.cmd { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12px;
  color:var(--muted); user-select:all; }
.diff { margin:0; overflow-x:auto; font-family: ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:12px; line-height:1.55; }
.diff .row { display:flex; align-items:stretch; min-width:max-content; }
.diff .gut { flex:0 0 66px; display:flex; align-items:center; gap:6px; padding:0 8px 0 8px;
  color:var(--muted); user-select:none; white-space:pre; }
.diff .gut .tick { margin:0; flex:0 0 auto; cursor:pointer; }
.diff .gut .num { flex:1 1 auto; text-align:right; }
/* A ticked line is the thing being sent, so it is marked as such rather than left to be
   found by re-reading every checkbox. */
.diff .row.picked .code { box-shadow: inset 3px 0 0 var(--inform); }
.diff .code { flex:1 1 auto; padding:0 12px; white-space:pre; }
.diff .code.a { background:var(--add); }
.diff .code.d { background:var(--del); }
.diff .code.h { color:var(--muted); }
.diff .code.m { color:var(--muted); font-weight:600; }
/* A comment sits under the line it is about, indented past the gutter so the diff still
   reads as a column. */
.diff .comment { display:flex; padding:6px 12px 8px 66px; gap:8px; align-items:flex-start;
  background:var(--card); border-top:1px solid var(--line); border-bottom:1px solid var(--line); }
.diff .comment textarea { flex:1 1 auto; font:inherit; font-family:inherit; min-height:48px;
  padding:6px 8px; border:1px solid var(--line); border-radius:6px; background:var(--bg);
  color:var(--fg); resize:vertical; }
.diff .comment .said { flex:1 1 auto; white-space:pre-wrap; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; font-size:13px; }
.diff .comment .acts { display:flex; flex-direction:column; gap:4px; }
.diff .comment button { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; font-size:12px; padding:3px 9px; border-radius:6px;
  border:1px solid var(--line); background:var(--bg); color:var(--fg); cursor:pointer; }
.diff .comment button.primary { background:var(--inform); color:#fff; border-color:var(--inform); }
.empty { color:var(--muted); }
footer { position:fixed; left:0; right:0; bottom:0; border-top:1px solid var(--line);
  background:var(--bg); padding:12px 16px; display:flex; align-items:center; gap:16px;
  justify-content:center; }
footer .count { font-weight:600; }
footer .wait { color:var(--muted); font-size:12px; }
`;

/**
 * How much of one file's patch the page will draw.
 *
 * The buffer the patch is read through was raised to 256 MiB so that a large change can be
 * reviewed at all — before that, `shipkit review` simply exited 2 on one. Raising it without
 * this would have moved the failure rather than fixed it: the same change that used to throw
 * would instead be rendered, one `<span>` per line, into a page that locks the tab.
 *
 * A quarter of a mebibyte is roughly three thousand lines of source — past any hunk a person
 * reads in a browser, and far short of what a browser struggles with. Beyond it the file
 * keeps its row, its status and its Open button, and the patch is named rather than drawn:
 * the editor is the right place to read three thousand lines, and the page says so.
 */
const MAX_PATCH_CHARS = 256 * 1024;

/**
 * The new-file line number a diff line sits on, or `undefined` where there is none.
 *
 * Tracked across the whole patch rather than guessed per line, because only the hunk headers
 * say where a hunk starts: `@@ -12,7 +34,9 @@` means the next added-or-context line is line
 * 34 of the file after the change. A removed line has no number on that side — it is not in
 * the file any more — so it gets none, and cannot be commented on. That is the same rule
 * GitHub applies, and for the same reason: a note anchored to a line that no longer exists
 * cannot be found by anyone, agent or person.
 */
function withLineNumbers(patch: string): { text: string; cls: string; line?: number }[] {
  const rows: { text: string; cls: string; line?: number }[] = [];
  let next: number | undefined;
  for (const line of patch.split("\n")) {
    if (line.startsWith("@@")) {
      const match = /^@@ -\d+(?:,\d+)? \+(\d+)/.exec(line);
      next = match === null ? undefined : Number(match[1]);
      rows.push({ text: line, cls: "h" });
      continue;
    }
    if (line.startsWith("+++") || line.startsWith("---") || line.startsWith("diff --git ")) {
      rows.push({ text: line, cls: "m" });
      continue;
    }
    if (line.startsWith("-")) {
      rows.push({ text: line, cls: "d" });
      continue;
    }
    if (next === undefined) {
      rows.push({ text: line, cls: line.startsWith("+") ? "a" : "" });
      continue;
    }
    rows.push({ text: line, cls: line.startsWith("+") ? "a" : "", line: next });
    next += 1;
  }
  return rows;
}

/**
 * One row per diff line, each carrying the line number it sits on so a person can write on
 * it.
 *
 * The row, not a `<span>`: a comment has to open *under* the line it is about, which needs a
 * block to insert after. The gutter is a separate cell rather than characters in the text so
 * that copying the diff copies the diff and not the numbering.
 */
function renderPatch(path: string, patch: string): string {
  if (patch.length > MAX_PATCH_CHARS) {
    const lines = patch.split("\n").length;
    return (
      `<div class="diff"><div class="row"><span class="gut"></span><span class="h">  ` +
      `${lines.toLocaleString("en-US")} lines of diff — too much to draw here. Open the file to ` +
      `read it; everything else on this page still covers it.</span></div></div>`
    );
  }
  if (patch.length === 0) {
    return `<div class="diff"><div class="row"><span class="gut"></span><span class="h">  No textual diff — a binary file, or a mode change only.</span></div></div>`;
  }
  const rows = withLineNumbers(patch).map((row) => {
    // A blank line inside a patch is a context line whose content is empty; without the
    // space the row collapses to zero height and the hunk loses a row.
    const text = row.text.length === 0 ? " " : row.text;
    if (row.line === undefined) {
      return `<div class="row"><span class="gut"><span class="num">${escapeHtml("")}</span></span><span class="code ${row.cls}">${escapeHtml(text)}</span></div>`;
    }
    return (
      `<div class="row" data-path="${escapeHtml(path)}" data-line="${row.line}">` +
      `<span class="gut">` +
      `<input type="checkbox" class="tick" title="Send this line to the agent">` +
      `<span class="num">${row.line}</span>` +
      `</span>` +
      `<span class="code ${row.cls}">${escapeHtml(text)}</span>` +
      `</div>`
    );
  });
  return `<div class="diff">${rows.join("")}</div>`;
}

function renderItem(item: ReviewItem, index: number): string {
  const label =
    item.severity === "refuses" ? "refuses" : item.severity === "warns" ? "warns" : "advises";
  return [
    `<div class="card ${item.severity}" data-index="${index}">`,
    `<div class="top">`,
    `<input type="checkbox" id="pick-${index}" data-pick="${index}">`,
    `<span class="badge">${escapeHtml(item.kind)} · ${escapeHtml(label)}</span>`,
    `<span class="id">${escapeHtml(item.id)}</span>`,
    `</div>`,
    `<div class="msg">${escapeHtml(item.message)}</div>`,
    `<textarea data-note="${index}" placeholder="Note to the agent (optional)"></textarea>`,
    `</div>`,
  ].join("");
}

function renderFile(file: PushFileDiff): string {
  const command = `xed --line ${file.line} ${file.path}`;
  return [
    `<section class="file">`,
    `<div class="head">`,
    `<span class="path">${escapeHtml(file.path)}</span>`,
    `<span class="status">${escapeHtml(file.status)}</span>`,
    `<span class="spacer"></span>`,
    `<code class="cmd">${escapeHtml(command)}</code>`,
    `<button data-open="${escapeHtml(file.path)}" data-line="${file.line}">Open in Xcode</button>`,
    `</div>`,
    renderPatch(file.path, file.patch),
    `</section>`,
  ].join("");
}

/**
 * The page's own script.
 *
 * It reads the token out of a `data-` attribute rather than having it interpolated into a
 * JavaScript string literal: the attribute value goes through `escapeHtml` like everything
 * else, so there is exactly one escaping rule in this file instead of two.
 *
 * The items travel the same way — one `data-item` attribute per card, holding the kind, id
 * and message as JSON. Serialising them into a script literal would need JSON-inside-JS
 * escaping, which is a second rule and the one that usually goes wrong.
 */
const SCRIPT = `
(function () {
  var body = document.body;
  var token = body.getAttribute("data-token");
  var items = JSON.parse(body.getAttribute("data-items"));
  var picks = Array.prototype.slice.call(document.querySelectorAll("[data-pick]"));
  var count = document.getElementById("count");
  var send = document.getElementById("send");
  var nothing = document.getElementById("nothing");

  // Line comments, keyed by "path:line" so two notes on one line replace rather than stack —
  // the id is what an agent reads as the place, and two items with one id is the ambiguity
  // the readiness loader refuses for the same reason.
  var comments = {};

  function selected() {
    return picks.filter(function (box) { return box.checked; });
  }
  function commentCount() {
    return Object.keys(comments).length;
  }
  function refresh() {
    var ticked = selected().length;
    var written = commentCount();
    var parts = [];
    if (items.length > 0) parts.push(ticked + " of " + items.length + " selected");
    if (written > 0) parts.push(written + (written === 1 ? " line comment" : " line comments"));
    count.textContent = parts.length === 0 ? "Nothing selected" : parts.join(" · ");
  }
  picks.forEach(function (box) { box.addEventListener("change", refresh); });
  refresh();

  function rowKey(row) {
    return row.getAttribute("data-path") + ":" + row.getAttribute("data-line");
  }

  function noteBlock(row) {
    var next = row.nextElementSibling;
    return next && next.className === "comment" ? next : null;
  }

  /**
   * A ticked line is already an instruction: "fix this". The note is optional, so the field
   * is offered rather than demanded — a person who only ticks has still said something.
   */
  function openNote(row, key) {
    if (noteBlock(row)) return;
    var block = document.createElement("div");
    block.className = "comment";
    var field = document.createElement("textarea");
    field.placeholder = "Anything to add about this line? (optional)";
    field.value = comments[key].note;
    field.addEventListener("input", function () {
      comments[key].note = field.value.trim();
    });
    field.addEventListener("keydown", function (event) {
      if (event.key === "Escape") { field.blur(); }
    });
    block.appendChild(field);
    row.parentNode.insertBefore(block, row.nextSibling);
    return field;
  }

  function closeNote(row) {
    var block = noteBlock(row);
    if (block) block.parentNode.removeChild(block);
  }

  function pickLine(row, on) {
    var key = rowKey(row);
    row.className = on ? "row picked" : "row";
    if (!on) {
      delete comments[key];
      closeNote(row);
      refresh();
      return;
    }
    comments[key] = {
      kind: "comment",
      id: key,
      // The line itself, so an agent that has the note but not this page can find the place
      // even after the line numbers have moved under it.
      message: row.querySelector(".code").textContent,
      note: comments[key] ? comments[key].note : ""
    };
    var field = openNote(row, key);
    if (field) field.focus();
    refresh();
  }

  document.addEventListener("change", function (event) {
    var tick = event.target;
    if (!tick.classList || !tick.classList.contains("tick")) return;
    pickLine(tick.closest(".row"), tick.checked);
  });

  // The per-file "Open in Xcode" button. Confined on the server to the set of paths the page
  // itself offered — see src/review/server.ts — so this only ever names one of them.
  document.addEventListener("click", function (event) {
    var button = event.target.closest ? event.target.closest("[data-open]") : null;
    if (!button) return;
    fetch("/open?token=" + encodeURIComponent(token), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ path: button.getAttribute("data-open"), line: Number(button.getAttribute("data-line")) })
    }).then(function (response) {
      if (!response.ok) { button.textContent = "Could not open"; }
    }).catch(function () { button.textContent = "Could not open"; });
  });

  function post(chosen, describe) {
    send.disabled = true;
    nothing.disabled = true;
    fetch("/submit?token=" + encodeURIComponent(token), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ items: chosen })
    }).then(function (response) {
      if (!response.ok) throw new Error(String(response.status));
      count.textContent = describe;
      send.textContent = "Sent";
    }).catch(function () {
      send.disabled = false;
      nothing.disabled = false;
      count.textContent = "Could not send. Is shipkit still waiting?";
    });
  }

  nothing.addEventListener("click", function () {
    // Its own gesture, never the side effect of pressing the default button. An empty
    // selection also clears whatever a previous review left pending.
    post([], "Sent: nothing to fix. You can close this tab.");
  });

  send.addEventListener("click", function () {
    var chosen = selected().map(function (box) {
      var index = Number(box.getAttribute("data-pick"));
      var note = document.querySelector('[data-note="' + index + '"]');
      var item = items[index];
      return { kind: item.kind, id: item.id, message: item.message, note: note ? note.value.trim() : "" };
    });
    // Line comments go in the same list. They are not shipkit's findings, but they are the
    // same thing to the agent: something a person read this diff and asked for.
    Object.keys(comments).forEach(function (key) { chosen.push(comments[key]); });
    if (chosen.length === 0) {
      count.textContent = "Tick a finding or a line first, or choose Nothing to fix.";
      return;
    }
    post(chosen, "Sent " + chosen.length + " to shipkit. You can close this tab.");
  });
})();
`;

export function renderPage(input: PageInput): string {
  // Only what the selection file needs. The severity and the note stay on the page: the
  // first is shipkit's own judgement and belongs to this run, the second is typed after
  // this JSON is written.
  const payload = input.items.map((item) => ({
    kind: item.kind,
    id: item.id,
    message: item.message,
  }));

  const head = [
    `<header class="page">`,
    `<h1>${escapeHtml(input.repo)}</h1>`,
    `<div class="refs">${escapeHtml(input.branch)} &rarr; ${escapeHtml(input.base)}</div>`,
    input.commitMessage === undefined
      ? `<p class="subject none">No commit message — this review was run without an agent's answer, so nothing has been drafted yet.</p>`
      : `<p class="subject">${escapeHtml(input.commitMessage)}</p>`,
    `<pre class="stat">${escapeHtml(input.diffstat.length > 0 ? input.diffstat : "(no change against the base)")}</pre>`,
    ...(input.answered
      ? []
      : [
          `<p class="note-line">Readiness answers are absent — no response file was given, so nobody has answered the team's checklist yet.</p>`,
        ]),
    ...input.notes.map((note) => `<p class="note-line">${escapeHtml(note)}</p>`),
    `</header>`,
  ].join("");

  const findings =
    input.items.length === 0
      ? `<p class="empty">Nothing to report. shipkit found no findings, no warnings and nothing to advise.</p>`
      : input.items.map(renderItem).join("");

  const files =
    input.files.length === 0
      ? `<p class="empty">The push carries no files.</p>`
      : input.files.map(renderFile).join("");

  return [
    `<!doctype html>`,
    `<html lang="en"><head><meta charset="utf-8">`,
    `<meta name="viewport" content="width=device-width,initial-scale=1">`,
    `<title>shipkit review — ${escapeHtml(input.branch)}</title>`,
    `<style>${STYLE}</style></head>`,
    `<body data-token="${escapeHtml(input.token)}" data-items="${escapeHtml(JSON.stringify(payload))}">`,
    `<main>`,
    head,
    `<h2>What shipkit has to say</h2>`,
    findings,
    `<h2>The change</h2>`,
    files,
    `</main>`,
    `<footer>`,
    `<span class="count" id="count">Nothing selected</span>`,
    // Two buttons, because "fix these" and "this is fine" are two statements. The menu-bar
    // panel learned this the expensive way: one button whose words changed with what was
    // ticked read as the only option, and a person with an unread list pressed it.
    `<button class="primary" id="send">Send to the agent</button>`,
    `<button id="nothing">Nothing to fix</button>`,
    `<span class="wait">shipkit is waiting for up to ${input.waitMinutes} minutes.</span>`,
    `</footer>`,
    `<script>${SCRIPT}</script>`,
    `</body></html>`,
  ].join("");
}
