import type { PushFileDiff } from "../vcs/git.js";
import type { ReviewItem } from "./items.js";

/**
 * The review page: one self-contained HTML document, no framework, no CDN, no request to
 * anything but the loopback origin that served it.
 *
 * Generated by TypeScript rather than a template file so that it is testable — the suite
 * asserts that the findings are present, that a message containing `<script>` or a quote
 * cannot break out of the markup, and that the page will not submit without the token.
 */

/**
 * The five characters that can move a value from HTML text into HTML markup.
 *
 * `&` first and unconditionally, or escaping `<` to `&lt;` would then have its own `&`
 * escaped again. Quotes are included because attribute values are interpolated too (the
 * token, the file paths), and `'` because a single-quoted attribute is a legal thing for
 * this file to grow later — escaping only what today's quoting style needs is how a future
 * edit reintroduces the hole.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export type PageInput = {
  /** The repository's directory name — what a person calls it, not its absolute path. */
  repo: string;
  branch: string;
  base: string;
  /**
   * The message the commit will carry, from the agent's answer. Absent when `review` was
   * run without one, which is its own thing worth showing.
   */
  commitMessage?: string | undefined;
  /** `readPushDiffstat`'s answer: the size of what the push will deliver. */
  diffstat: string;
  items: ReviewItem[];
  files: PushFileDiff[];
  /** True when an `--input` response supplied readiness answers. */
  answered: boolean;
  /** Anything shipkit could not do, said plainly — e.g. the forge was unreachable. */
  notes: string[];
  /** The single-use secret the page must send back. Without it the POST is refused. */
  token: string;
  /** How long the command will wait, in whole minutes, so the page can say so. */
  waitMinutes: number;
};

const STYLE = `
:root { color-scheme: light dark; --fg:#1f2328; --bg:#ffffff; --muted:#59636e; --line:#d1d9e0;
  --card:#f6f8fa; --refuse:#cf222e; --warn:#9a6700; --inform:#0969da; --add:#e6ffec; --del:#ffebe9; }
@media (prefers-color-scheme: dark) { :root { --fg:#e6edf3; --bg:#0d1117; --muted:#9198a1;
  --line:#3d444d; --card:#151b23; --refuse:#ff7b72; --warn:#d29922; --inform:#4493f8;
  --add:#12261e; --del:#25171c; } }
* { box-sizing: border-box; }
body { margin:0; padding:0 0 88px; font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  color:var(--fg); background:var(--bg); }
main { max-width: 1000px; margin: 0 auto; padding: 24px 16px; }
header.page { border-bottom:1px solid var(--line); padding-bottom:16px; margin-bottom:24px; }
h1 { font-size:20px; margin:0 0 6px; }
h2 { font-size:15px; margin:28px 0 10px; }
.refs { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; color:var(--muted); }
.subject { margin:10px 0 0; font-weight:600; white-space:pre-wrap; }
.subject.none { font-weight:400; color:var(--muted); }
pre.stat { margin:10px 0 0; font-family: ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:12px; color:var(--muted); overflow-x:auto; }
.note-line { margin:10px 0 0; color:var(--warn); font-size:13px; }
.card { border:1px solid var(--line); border-left-width:4px; border-radius:6px;
  background:var(--card); padding:12px 14px; margin:0 0 10px; }
.card.refuses { border-left-color:var(--refuse); }
.card.warns  { border-left-color:var(--warn); }
.card.informs{ border-left-color:var(--inform); }
.card .top { display:flex; align-items:baseline; gap:8px; }
.card input[type=checkbox] { width:16px; height:16px; margin:2px 4px 0 0; flex:none; align-self:flex-start; }
.badge { font-size:11px; text-transform:uppercase; letter-spacing:.04em; font-weight:700; }
.card.refuses .badge { color:var(--refuse); }
.card.warns .badge { color:var(--warn); }
.card.informs .badge { color:var(--inform); }
.id { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12px; color:var(--muted); }
.msg { margin:6px 0 0 24px; white-space:pre-wrap; }
.card textarea { margin:8px 0 0 24px; width:calc(100% - 24px); min-height:38px; resize:vertical;
  font:inherit; padding:6px 8px; border:1px solid var(--line); border-radius:6px;
  background:var(--bg); color:var(--fg); }
.file { border:1px solid var(--line); border-radius:6px; margin:0 0 14px; overflow:hidden; }
.file > .head { display:flex; align-items:center; gap:10px; flex-wrap:wrap;
  background:var(--card); padding:8px 12px; border-bottom:1px solid var(--line); }
.file .path { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-weight:600; }
.file .status { font-size:11px; text-transform:uppercase; color:var(--muted); }
.file .spacer { flex:1; }
button { font:inherit; padding:4px 10px; border:1px solid var(--line); border-radius:6px;
  background:var(--bg); color:var(--fg); cursor:pointer; }
button.primary { background:var(--inform); border-color:var(--inform); color:#fff; font-weight:600;
  padding:8px 18px; }
button:disabled { opacity:.55; cursor:default; }
code.cmd { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12px;
  color:var(--muted); user-select:all; }
pre.diff { margin:0; overflow-x:auto; font-family: ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:12px; line-height:1.45; }
pre.diff span { display:block; padding:0 12px; white-space:pre; }
pre.diff .a { background:var(--add); }
pre.diff .d { background:var(--del); }
pre.diff .h { color:var(--muted); }
pre.diff .m { color:var(--muted); font-weight:600; }
.empty { color:var(--muted); }
footer { position:fixed; left:0; right:0; bottom:0; border-top:1px solid var(--line);
  background:var(--bg); padding:12px 16px; display:flex; align-items:center; gap:16px;
  justify-content:center; }
footer .count { font-weight:600; }
footer .wait { color:var(--muted); font-size:12px; }
`;

/**
 * How much of one file's patch the page will draw.
 *
 * The buffer the patch is read through was raised to 256 MiB so that a large change can be
 * reviewed at all — before that, `shipkit review` simply exited 2 on one. Raising it without
 * this would have moved the failure rather than fixed it: the same change that used to throw
 * would instead be rendered, one `<span>` per line, into a page that locks the tab.
 *
 * A quarter of a mebibyte is roughly three thousand lines of source — past any hunk a person
 * reads in a browser, and far short of what a browser struggles with. Beyond it the file
 * keeps its row, its status and its Open button, and the patch is named rather than drawn:
 * the editor is the right place to read three thousand lines, and the page says so.
 */
const MAX_PATCH_CHARS = 256 * 1024;

/** One `<span>` per diff line, classed by its marker so a hunk reads at a glance. */
function renderPatch(patch: string): string {
  if (patch.length > MAX_PATCH_CHARS) {
    const lines = patch.split("\n").length;
    return (
      `<pre class="diff"><span class="h">  ${lines.toLocaleString("en-US")} lines of diff — too much to ` +
      `draw here. Open the file to read it; everything else on this page still covers it.</span></pre>`
    );
  }
  if (patch.length === 0) {
    return `<pre class="diff"><span class="h">  No textual diff — a binary file, or a mode change only.</span></pre>`;
  }
  const lines = patch.split("\n").map((line) => {
    let cls = "";
    if (line.startsWith("+++") || line.startsWith("---") || line.startsWith("diff --git ")) cls = "m";
    else if (line.startsWith("@@")) cls = "h";
    else if (line.startsWith("+")) cls = "a";
    else if (line.startsWith("-")) cls = "d";
    // A blank line inside a patch is a context line whose content is empty; without the
    // space the `<span>` collapses to zero height and the hunk loses a row.
    const text = line.length === 0 ? " " : line;
    return `<span class="${cls}">${escapeHtml(text)}</span>`;
  });
  return `<pre class="diff">${lines.join("")}</pre>`;
}

function renderItem(item: ReviewItem, index: number): string {
  const label =
    item.severity === "refuses" ? "refuses" : item.severity === "warns" ? "warns" : "advises";
  return [
    `<div class="card ${item.severity}" data-index="${index}">`,
    `<div class="top">`,
    `<input type="checkbox" id="pick-${index}" data-pick="${index}">`,
    `<span class="badge">${escapeHtml(item.kind)} · ${escapeHtml(label)}</span>`,
    `<span class="id">${escapeHtml(item.id)}</span>`,
    `</div>`,
    `<div class="msg">${escapeHtml(item.message)}</div>`,
    `<textarea data-note="${index}" placeholder="Note to the agent (optional)"></textarea>`,
    `</div>`,
  ].join("");
}

function renderFile(file: PushFileDiff): string {
  const command = `xed --line ${file.line} ${file.path}`;
  return [
    `<section class="file">`,
    `<div class="head">`,
    `<span class="path">${escapeHtml(file.path)}</span>`,
    `<span class="status">${escapeHtml(file.status)}</span>`,
    `<span class="spacer"></span>`,
    `<code class="cmd">${escapeHtml(command)}</code>`,
    `<button data-open="${escapeHtml(file.path)}" data-line="${file.line}">Open in Xcode</button>`,
    `</div>`,
    renderPatch(file.patch),
    `</section>`,
  ].join("");
}

/**
 * The page's own script.
 *
 * It reads the token out of a `data-` attribute rather than having it interpolated into a
 * JavaScript string literal: the attribute value goes through `escapeHtml` like everything
 * else, so there is exactly one escaping rule in this file instead of two.
 *
 * The items travel the same way — one `data-item` attribute per card, holding the kind, id
 * and message as JSON. Serialising them into a script literal would need JSON-inside-JS
 * escaping, which is a second rule and the one that usually goes wrong.
 */
const SCRIPT = `
(function () {
  var body = document.body;
  var token = body.getAttribute("data-token");
  var items = JSON.parse(body.getAttribute("data-items"));
  var picks = Array.prototype.slice.call(document.querySelectorAll("[data-pick]"));
  var count = document.getElementById("count");
  var send = document.getElementById("send");

  function selected() {
    return picks.filter(function (box) { return box.checked; });
  }
  function refresh() {
    count.textContent = selected().length + " of " + items.length + " selected";
  }
  picks.forEach(function (box) { box.addEventListener("change", refresh); });
  refresh();

  document.addEventListener("click", function (event) {
    var button = event.target.closest ? event.target.closest("[data-open]") : null;
    if (!button) return;
    fetch("/open?token=" + encodeURIComponent(token), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ path: button.getAttribute("data-open"), line: Number(button.getAttribute("data-line")) })
    }).then(function (response) {
      if (!response.ok) { button.textContent = "Could not open"; }
    }).catch(function () { button.textContent = "Could not open"; });
  });

  send.addEventListener("click", function () {
    send.disabled = true;
    var chosen = selected().map(function (box) {
      var index = Number(box.getAttribute("data-pick"));
      var note = document.querySelector('[data-note="' + index + '"]');
      var item = items[index];
      return { kind: item.kind, id: item.id, message: item.message, note: note ? note.value.trim() : "" };
    });
    fetch("/submit?token=" + encodeURIComponent(token), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ items: chosen })
    }).then(function (response) {
      if (!response.ok) throw new Error(String(response.status));
      count.textContent = chosen.length === 0
        ? "Nothing selected. You can close this tab."
        : "Sent " + chosen.length + " to shipkit. You can close this tab.";
      send.textContent = "Sent";
    }).catch(function () {
      send.disabled = false;
      count.textContent = "Could not send. Is shipkit still waiting?";
    });
  });
})();
`;

export function renderPage(input: PageInput): string {
  // Only what the selection file needs. The severity and the note stay on the page: the
  // first is shipkit's own judgement and belongs to this run, the second is typed after
  // this JSON is written.
  const payload = input.items.map((item) => ({
    kind: item.kind,
    id: item.id,
    message: item.message,
  }));

  const head = [
    `<header class="page">`,
    `<h1>${escapeHtml(input.repo)}</h1>`,
    `<div class="refs">${escapeHtml(input.branch)} &rarr; ${escapeHtml(input.base)}</div>`,
    input.commitMessage === undefined
      ? `<p class="subject none">No commit message — this review was run without an agent's answer, so nothing has been drafted yet.</p>`
      : `<p class="subject">${escapeHtml(input.commitMessage)}</p>`,
    `<pre class="stat">${escapeHtml(input.diffstat.length > 0 ? input.diffstat : "(no change against the base)")}</pre>`,
    ...(input.answered
      ? []
      : [
          `<p class="note-line">Readiness answers are absent — no response file was given, so nobody has answered the team's checklist yet.</p>`,
        ]),
    ...input.notes.map((note) => `<p class="note-line">${escapeHtml(note)}</p>`),
    `</header>`,
  ].join("");

  const findings =
    input.items.length === 0
      ? `<p class="empty">Nothing to report. shipkit found no findings, no warnings and nothing to advise.</p>`
      : input.items.map(renderItem).join("");

  const files =
    input.files.length === 0
      ? `<p class="empty">The push carries no files.</p>`
      : input.files.map(renderFile).join("");

  return [
    `<!doctype html>`,
    `<html lang="en"><head><meta charset="utf-8">`,
    `<meta name="viewport" content="width=device-width,initial-scale=1">`,
    `<title>shipkit review — ${escapeHtml(input.branch)}</title>`,
    `<style>${STYLE}</style></head>`,
    `<body data-token="${escapeHtml(input.token)}" data-items="${escapeHtml(JSON.stringify(payload))}">`,
    `<main>`,
    head,
    `<h2>What shipkit has to say</h2>`,
    findings,
    `<h2>The change</h2>`,
    files,
    `</main>`,
    `<footer>`,
    `<span class="count" id="count">0 of ${input.items.length} selected</span>`,
    `<button class="primary" id="send">Send to shipkit</button>`,
    `<span class="wait">shipkit is waiting for up to ${input.waitMinutes} minutes.</span>`,
    `</footer>`,
    `<script>${SCRIPT}</script>`,
    `</body></html>`,
  ].join("");
}
