import Foundation
import Testing
@testable import ShipkitKit

/// The cross-language contract for a review offer.
///
/// The fixture is the contract, not either implementation. These vectors were
/// generated by `src/approval/fingerprint.ts` and are recomputed here from the
/// Swift canonical form — so a change to either side that the other does not
/// match fails here rather than at a person's menu bar, where it would look
/// like a refusal nobody can explain.
private struct ReviewVector: Decodable {
    struct Sit: Decodable {
        let repo, root, branch, base, commitMessage, diffstat: String
        let items: [OfferedItem]
        let files: [OfferedFile]
    }
    let name: String
    let situation: Sit
    let fingerprint: String
}

private func loadReviewVectors() throws -> [ReviewVector] {
    var url = URL(fileURLWithPath: #filePath)
    for _ in 0..<5 { url.deleteLastPathComponent() }
    url.appendPathComponent("tests/fixtures/review-fingerprint-vectors.json")
    return try JSONDecoder().decode([ReviewVector].self, from: Data(contentsOf: url))
}

private func situation(_ vector: ReviewVector) -> ReviewSituation {
    ReviewSituation(
        repo: vector.situation.repo,
        root: vector.situation.root,
        branch: vector.situation.branch,
        base: vector.situation.base,
        commitMessage: vector.situation.commitMessage,
        diffstat: vector.situation.diffstat,
        items: vector.situation.items,
        files: vector.situation.files
    )
}

@Test func matchesEveryReviewVectorInTheSharedFixture() throws {
    let vectors = try loadReviewVectors()
    #expect(vectors.count >= 5)

    for vector in vectors {
        #expect(reviewFingerprint(situation(vector)) == vector.fingerprint, "vector: \(vector.name)")
    }
}

/// Items are hashed in the order they arrive, never sorted. Refusals come
/// first, then warnings, then advice, and that order is part of what the person
/// reads — sorting would hash something other than what is shown.
@Test func hashesItemsInTheOrderTheyArrive() throws {
    let vectors = try loadReviewVectors()
    let ordered = try #require(vectors.first { $0.situation.items.count == 2 })
    let forward = situation(ordered)
    let reversed = ReviewSituation(
        repo: forward.repo, root: forward.root, branch: forward.branch, base: forward.base,
        commitMessage: forward.commitMessage, diffstat: forward.diffstat,
        items: forward.items.reversed(), files: forward.files
    )

    #expect(reviewFingerprint(forward) != reviewFingerprint(reversed))
}

/// Length-prefixed rather than delimited, so a message carrying a newline or a
/// `12:` cannot be read as two fields — the disagreement that would otherwise
/// wait for the first message that contains one.
@Test func aMessageCarryingTheDelimitersStillMatches() throws {
    let vectors = try loadReviewVectors()
    let torture = try #require(vectors.first { $0.name.contains("delimiters") })

    #expect(reviewFingerprint(situation(torture)) == torture.fingerprint)
}

/// An approval and a review of the same repository are different questions, and
/// their canonical forms carry different version markers so they can never
/// collide even if every shared field happened to agree.
@Test func aReviewIsNeverAnApproval() {
    let review = ReviewSituation(
        repo: "x", root: "/tmp/x", branch: "b", base: "develop",
        commitMessage: "", diffstat: "", items: [], files: []
    )
    let approval = Situation(
        repo: "x", branch: "b", base: "develop", head: "", title: "",
        commitMessage: "", diffstat: "", warnings: []
    )

    #expect(reviewFingerprint(review) != fingerprint(approval))
}

/// The checkout path is bound even though the panel never shows it: it decides
/// which file on this machine the editor button opens, and a field that steers
/// a side effect must not be changeable between the hash and the click.
@Test func twoCheckoutsOfTheSameBranchAreTwoReviews() {
    let one = ReviewSituation(
        repo: "example-app", root: "/Users/x/example-app", branch: "b", base: "develop",
        commitMessage: "", diffstat: "",
        items: [], files: [OfferedFile(path: "A.swift", status: "modified", line: 1)]
    )
    let other = ReviewSituation(
        repo: "example-app", root: "/Users/x/second-checkout", branch: "b", base: "develop",
        commitMessage: "", diffstat: "",
        items: [], files: [OfferedFile(path: "A.swift", status: "modified", line: 1)]
    )

    #expect(reviewFingerprint(one) != reviewFingerprint(other))
}
